language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls"
  - "pip install pymongo==2.8"
  - "pip install flask-mongoengine==0.7.1"
  - "pip install Pillow"
services:
  - mongodb
script:
  - coverage run --source=flask_appbuilder --omit=*messages.py*,*baseapp.py* setup.py test
after_success:
  coveralls
